### ISSUE TITLE
Ir takes all the html as plain text [HELP]

### ISSUE THREAD

**Issue by neondeex** [Blumlaut/xenforo-resource-discord-bot#1]
![image](https://user-images.githubusercontent.com/30392593/149635286-f616e91b-25c3-47e5-96e5-123553a7618c.png)

**Comment by Blumlaut** [comment]
Do you have a link of a page where this happens? offending code is here:
https://github.com/Blumlaut/xenforo-resource-discord-bot/blob/957ccba283eb6d3c065b688f621eed8b1df185cb/rd-bot.js#L61

**Comment by neondeex** [comment]
spigot.es

**Comment by Blumlaut** [comment]
in your case the bot picks up the "tag" as resource name, change 
```js
var latestName = latest.querySelector(".structItem-title").children[0].innerHTML
```
to
```js
var latestName = latest.querySelector(".structItem-title").children[1].innerHTML
```

since the actual title has no Class Name you have to go off index.

**Comment by neondeex** [comment]
That ill fix all of this?
![image](https://user-images.githubusercontent.com/30392593/149641871-b1828add-d046-40f1-b39d-fdd13fa67d8d.png)

**Comment by Blumlaut** [comment]
> That ill fix all of this?

i personally couldn't reproduce this on my end:
![image](https://user-images.githubusercontent.com/13604413/149641883-8d593ffc-000b-4691-8861-fa8f6c07e02b.png)


is there a specific category this happens in? If so link it please

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/149641938-3a7fa2c8-4589-44ea-96f2-92e993de8ec5.png)
fix title but not author

**Comment by Blumlaut** [comment]
try this:
https://github.com/Blumlaut/xenforo-resource-discord-bot/commit/ed6d2072d6fd9bd1b5aff6a7a510dc533f7a4514

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/149642228-1433f6cb-fbd1-4209-a252-84f806d75526.png)

**Comment by Blumlaut** [comment]
run npm install.

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/149642267-f89679c0-7703-4165-8f2d-8e956957d79f.png)

**Comment by Blumlaut** [comment]
Is your node version outdated? run `node --version`, you should have 16 or above

also on an unrelated node, i just made another commit that adds a few config options, dont forget to update your config if you git pull-ed

**Comment by neondeex** [comment]
Works! 
![image](https://user-images.githubusercontent.com/30392593/149642380-c088fc3b-48d2-47c6-b125-8e57cfe81797.png)

**Comment by neondeex** [comment]
What is mod name?

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/149642431-0dd22a67-3b51-4936-abc8-f812d68c0fa4.png)
also is not fetching the resource icon

**Comment by Blumlaut** [comment]
> What is mod name?

latestName variable, you will probably need to make the change here: https://github.com/Blumlaut/xenforo-resource-discord-bot/issues/1#issuecomment-1013777109

again, as the bot is picking up the "tag" as a title name

>  also is not fetching the resource icon

make sure you fetched the last update and added the `PlaceholderImage` and `RootURL` parameters to your config.json i newly added (see the example config), should all work then:
![image](https://user-images.githubusercontent.com/13604413/149642537-2ca81b73-e35a-434e-b227-985af769118f.png)


as a todo would probably be automatically detecting the Root URL from the category url, but i honestly didn't think anyone actually used this 😅

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/149642834-8cff0d2b-63a2-4781-b5d4-21a3d4fd1f5a.png)
Changed like this but still don't get the resource IMG and the version and downloads is wrong
version gets me the title and downloads the text not the number

**Comment by Blumlaut** [comment]
argh! in my haste i messed up the downloads, i'll write a quick thing for you to detect the label automatically, that should also fix the version number, give me a few minutes!

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/xenforo-resource-discord-bot/commit/d6d607c635e9feefbf00d74867fe96ed166c45a7

should fix it, you should no longer need to manually edit the code.

The images seem to fetch fine on my end, so i'm not sure whats going wrong on your end sadly.
![image](https://user-images.githubusercontent.com/13604413/149643254-4445b304-a64f-44b9-9482-369cf0eddcdd.png)


Also, you should probably rotate your bot token! you leaked it with the screenshot

**Comment by Blumlaut** [comment]
let me know if theres still issues! With latest commit the end result is this:
![image](https://user-images.githubusercontent.com/13604413/149659804-6cc9c5d6-9659-44d0-8707-6ff9c31603fa.png)

It also directly links to the resource and fetches the image itself, RootURL parameter is no longer needed

**Comment by neondeex** [comment]
All working fine :3
